### ISSUE TITLE
Don't compil under gcc 5.4

### ISSUE THREAD

**Issue by alphaonex86** [mdally/Voronoi#3]
examples/Console_Example.cpp: In function 'int main()':
examples/Console_Example.cpp:68:10: error: no match for 'operator=' (operand types are 'std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >' and 'std::chrono::_V2::system_clock::time_point {aka std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >}')
    start = std::chrono::high_resolution_clock::now();
          ^
In file included from examples/Console_Example.cpp:11:0:
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/chrono:546:14: note: candidate: std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >& std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >::operator=(const std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >&)
       struct time_point
              ^
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/chrono:546:14: note:   no known conversion for argument 1 from 'std::chrono::_V2::system_clock::time_point {aka std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >}' to 'const std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >&'
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/chrono:546:14: note: candidate: std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >& std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >::operator=(std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >&&)
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/chrono:546:14: note:   no known conversion for argument 1 from 'std::chrono::_V2::system_clock::time_point {aka std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >}' to 'std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >&&'
examples/Console_Example.cpp:70:9: error: no match for 'operator=' (operand types are 'std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >' and 'std::chrono::_V2::system_clock::time_point {aka std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >}')
    stop = std::chrono::high_resolution_clock::now();                                                                                                                                         
         ^
In file included from examples/Console_Example.cpp:11:0:
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/chrono:546:14: note: candidate: std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >& std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >::operator=(const std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >&)                                                                                                         
       struct time_point                                                                                                                                                                      
              ^
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/chrono:546:14: note:   no known conversion for argument 1 from 'std::chrono::_V2::system_clock::time_point {aka std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >}' to 'const std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >&'
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/chrono:546:14: note: candidate: std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >& std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >::operator=(std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >&&)
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/chrono:546:14: note:   no known conversion for argument 1 from 'std::chrono::_V2::system_clock::time_point {aka std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >}' to 'std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >&&'
make: *** [makefile:28: examples/Console_Example.o] Error 1

**Comment by mdally** [comment]
Just pushed a change that should fix this. 

Let me know if it's still a problem for you.
